setup:
    general: !mux
        runltp: !mux
            script: 'runltp'
            crypto:
                args: '-f crypto'
            cve:
                args: '-f cve'
            ima:
                args: '-f ima'
            net_stress.ipsec_dccp:
                args: '-f net_stress.ipsec_dccp'
            net_stress.ipsec_icmp:
                args: '-f net_stress.ipsec_icmp'
            net_stress.ipsec_sctp:
                args: '-f net_stress.ipsec_sctp'
            net_stress.ipsec_tcp:
                args: '-f net_stress.ipsec_tcp'
            net_stress.ipsec_udp:
                args: '-f net_stress.ipsec_udp'
            securebits:
                args: '-f securebits'
            tpm_tools:
                args: '-f tpm_tools'
