kirk: !mux
    script: 'kirk'
    crashme:
        args: '-f crashme'
    crypto:
        args: '-f crypto'
    cve:
        args: '-f cve'
    ima:
        args: '-f ima'
    tpm_tools:
        args: '-f tpm_tools'
